services:
  fn-devcontainer-api:
    image: fn-devcontainer-api:es
    container_name: fn-devcontainer-api
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - 17777:7777
    volumes:
      - ./:/app/FN-Devcontainer-Services
    # restart: unless-stopped
    environment:
      - ES_HOST=http://host.docker.internal:9203
    networks:
      - bridge

volumes:
  ollama_data:
  open-webui_data:

networks:
  bridge:
    driver: bridge