services:
  fn-devcontainer-api:
    image: fn-devcontainer-api:es
    container_name: devcontainer-fastapi-uv
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
      target: runtime
    entrypoint: ./uv_fastapi_start.sh
    ports:
      - 8001:8000
    volumes:
      - ./:/workspace
    # restart: unless-stopped
    environment:
      - ES_HOST=http://host.docker.internal:9203
    networks:
      - bridge

  fn-devcontainer-api-test:
    image: fn-devcontainer-api-test:es
    container_name: devcontainer-fastapi-uv-test
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
      target: runtime
    entrypoint: ./pytest.sh
    ports:
      - 8002:8000
    volumes:
      - ./:/workspace
    # restart: unless-stopped
    environment:
      - ES_HOST=http://host.docker.internal:9203
    networks:
      - bridge


volumes:
  ollama_data:
  open-webui_data:

networks:
  bridge:
    driver: bridge